;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        isearch-forward-regexp
        isearch-printing-char
        paredit-forward-delete
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        ido-find-file
        smex
        yas-expand
        ))
